package com.amanullah.lazyrow.repository

import com.amanullah.lazyrow.model.Person

class PersonRepository {
    fun getAllData(): List<Person>
    {
        return listOf(
            Person(
                0,
                "Amanullah",
                "Sarker",
                1
            ),
            Person(
                1,
                "Amanullah",
                "Sarker",
                2
            ),
            Person(
                2,
                "Amanullah",
                "Sarker",
                3
            ),
            Person(
                3,
                "Amanullah",
                "Sarker",
                4
            ),
            Person(
                4,
                "Amanullah",
                "Sarker",
                5
            ),
            Person(
                5,
                "Amanullah",
                "Sarker",
                6
            ),
            Person(
                6,
                "Amanullah",
                "Sarker",
                7
            ),Person(
                7,
                "Amanullah",
                "Sarker",
                8
            ),
            Person(
                8,
                "Amanullah",
                "Sarker",
                9
            ),
            Person(
                9,
                "Amanullah",
                "Sarker",
                10
            ),
            Person(
                10,
                "Amanullah",
                "Sarker",
                11
            ),
            Person(
                11,
                "Amanullah",
                "Sarker",
                12
            ),
            Person(
                12,
                "Amanullah",
                "Sarker",
                13
            ),
            Person(
                13,
                "Amanullah",
                "Sarker",
                14
            ),
            Person(
                14,
                "Amanullah",
                "Sarker",
                15
            ),
            Person(
                15,
                "Amanullah",
                "Sarker",
                16
            ),
            Person(
                16,
                "Amanullah",
                "Sarker",
                17
            ),Person(
                17,
                "Amanullah",
                "Sarker",
                18
            ),
            Person(
                18,
                "Amanullah",
                "Sarker",
                19
            ),
            Person(
                19,
                "Amanullah",
                "Sarker",
                20
            )
        )
    }
}